networks:
  momo-store-swarm:
    driver: overlay
    attachable: true

services:
  backend:
    image: b10nicle/docker-project-backend:latest
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    expose:
      - "8081"
    networks:
      - momo-store-swarm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 20s
      retries: 5
      timeout: 15s
      start_period: 10s
    deploy:
      replicas: 3
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
          cpus: '0.5'

  frontend:
    image: b10nicle/docker-project-frontend:latest
    cap_add:
      - NET_BIND_SERVICE
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    cap_drop:
      - ALL
    ports:
      - "80:80"
    networks:
      - momo-store-swarm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 20s
      retries: 5
      timeout: 15s
      start_period: 10s
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
          cpus: '0.25'
